### ISSUE TITLE
Sajari Related Posts

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#101]

**Comment by jetlej** [comment]
@MSchirp - What logic/sorting should it use for showing posts?

**Comment by MSchirp** [comment]
I think we will need a third party software for this, it will be too complicated to do something ourselves. Ill do some research on this because I do know what I want.

**Comment by jetlej** [comment]
@MSchirp - Any luck on this? I doubt there are other services like Chartbeat that will allow for this functionality, so let's just decide on an algorithm that I can code up?

**Comment by JonBrooksX** [comment]
So for the sidebar blog posts I have a simple idea: 

25% highest earning articles (roughly 12 articles)
25% highest upvoted content (maybe 25 articles)
50% most recent articles of the last 20-30 days

Thoughts?

**Comment by jetlej** [comment]
Sounds good to me

**Comment by MSchirp** [comment]
I did some preliminary research on this, and there are companies that do exactly this. While your idea is good, Jon, what we want to optimise is recirculation. This happens when you can segment groups by interests, or, when you can show similar articles.

For instance, what Outbrain can do is: "Outbrain's algorithms look all all types of behaviors.... contextual (relevant), personal (content personalized for the user), popular (most popular articles) and collaborative (readers who have read this have also read....). Then our system optimizes for the reader."

**Comment by lostboyevsky** [comment]
jon's solution does sound simple and pretty good, but i'm definitely interested in the possibilities of the sort of product martijn is talking about. i know brain pickings uses Contextly, and i've used it in the past and really liked it. maybe that would work?

https://contextly.com

**Comment by JonBrooksX** [comment]
Contextly looks interesting. We'll be paying $100+ per month though. They have a 21-day free trial, we could compare my simple version to contextly.

**Comment by MSchirp** [comment]
Contently does look interesting, but their pricing goes linearly upwards, and so we would be paying more than we did for Chartbeat. 

Here is a list of similar technology we can use: https://www.similartech.com/categories/content-suggestion , going through them now.

**Comment by MSchirp** [comment]
What a mess, I find it very hard to find clear answers on which one is best in relation to cheapest. I'd say we keep Chartbeat if we want to go this road. After seeing the other options, i am convinced it earns itself back. 

@lostboyevsky Could you do a second opinion and check wether I missed something?

**Comment by lostboyevsky** [comment]
hmmmm, i just have a really hard time believing that $2500/year is a worthwhile investment to do something as seemingly simple as recommending related content. 

what exactly do we use from chartbeat that allows us to do this? is it just an algorithm that shows posts with the same tags? because i really think there are free wordpress plugins that do this. contextly was a bad call, didn't realize it gets so much more expensive with more visitors. one of the main reasons people like contextly, i think, is the sleek designs and customizability of the 'related content' widgets. however, we already have custom-designed widgets, so we don't really care about that stuff. all we need is a feature that includes an algorithm to plug in content with similar tags/keywords, no?

this one looks like it might work: https://wordpress.org/plugins/contextual-related-posts/

these all look potentially promising too: http://www.wpbeginner.com/plugins/5-best-related-posts-plugins-for-wordpress/

if there is a specific reason why these plugins algorithms won't work for us, i'm not sure i understand what it is we really need. maybe @jetlej can clarify? my intuitive sense is that it wouldn't even be that difficult to write an algorithm from scratch that shows related content based on keywords/tags. even if we paid a developer $500 to do this once, we would save **massive** amounts of money in the long-term. just imagine spending $25,000 on chartbeat over the course of the next 10 years and tell me that doesn't make you feel rather aghast.

**Comment by MSchirp** [comment]
You need to see that number in context before it can have any meaning whatsoever. For example, for simplicity, lets say we earn 8k a month and chart beat is $200. That is 2.5% of revenue. 

Lets also assume chart beat increases recirculation with 5% in comparison to plug ins because it can tell you which content is more engaging and so make people stick around longer. That means on average you earn $400 a month more using chart beat. In total, your ROI is $200 a month by using an external service that has a better algorithm to decide what is interesting for a specific individual. In essence, every time a user is on a page and an article you have that is interesting for that user, but isn't showing up, is a lost opportunity. Getting a good recommendation system has definitely a net plus expected value (+EV).

Now, the problem I faced is that it is very hard to tell which company would actually give us the highest recirculation. Their algorithms are private (and much more difficult to make than you can imagine). To push for these very tiny edges, that compound dramatically over time, you need a full analytics team. It's no surprise all bigger media platforms use at least one third party software to do this for them. Yes, it might cost 25k in the next 10 years. But it probably earns at least ±30k back. That doesn't make me feel aghast. 

What is annoying is that we can't reasonably decide between different offers because we don't have complete information. 

Regarding a plug: I think that is a big no, as your second article also suggests, this would slow a site with out traffic down way too much.

**Comment by jetlej** [comment]
@lostboyevsky - There are no good related post plugins for WP. I've done the research several times. There were some that outsourced the hard-work to the cloud, but those no longer exist for some reason. 

@MSchirp - Are you sure the companies you're looking at support same-site recommendations? Most of those are known for recommending content from other sites. 

Can you list the options you're considering?

**Comment by lostboyevsky** [comment]
yeah, i understand you argument, martijn. i just wish i knew for sure that chartbeat actually made back the value sunk into it and more. did you guys actually see recirculation increase significantly when you plugged in the chartbeat algorithm for sourcing the 'related posts' widgets? my experience has been that the related posts showing up in the sidebar seem to usually be a lot of the same articles -- some of our top articles -- and the ones at the bottom tend to be more diverse and based on the current post, but the algorithm doesn't seem that complex: it just seems like its sourcing content that is by the same author or has some of the same tags. i don't know.

jetpack claims its 'related posts' functionality uses the cloud and does not bog down sites, though i know jon has said before that jetpack in general *does* actually bog down sites: https://jetpack.me/support/related-posts/

still might be worth looking into

**Comment by MSchirp** [comment]
So I just typed out a long reply and lost if after safari crashing. :-1: 

Either way, the three options I am now considering are:

1) keeping with chart beat
2) going with outbrain
3) switching over to contextly 

1) advantage: not just recommended content, also good tracking. disadvantage: decent recommendation, not the best. too similar over time, not exactly related. price.
2) advantage: no costs for organic discovery. disadvantage: very little user control. 
3) advantage: best recommended content. Highly customisable. we could also use this for our front page. disadvantage: price. 

After doing another round through the big ones, other media companies etc. I think we should use contently and optimise it for our site. I am convinced it's worth it in the long haul.

**Comment by JonBrooksX** [comment]
Thanks, Martijn. I think if we had a price for Contextly based on our traffic stats we could make a better informed decision. So far Chartbeat still seems to have the edge to me.

**Comment by jetlej** [comment]
I just tried out Contextly. A few issues:

1) You have to manually pick related posts for every post. Huge issue. 

2) It won't allow us to correctly show images for videos, images, and anything else that does not have a featured image. There is no API, and all you can do is edit their widgets with CSS. Can't customize the code itself. 

3) It doesn't work on my local version at all...and the plugin has poor reviews.

**Comment by MSchirp** [comment]
Alright, so that is not an option then.

What were the different recommended options for chartbeat’s widget again? Their site is not really helpful, or I just don’t know where to look? Perhaps we can make a combination between their widget(s) and jetpack (which we are using now?)

**Comment by MSchirp** [comment]
That said, perhaps have a look at outbrain too. I think @jetlej is better in seeing if it can work or not.

**Comment by jetlej** [comment]
Checking into Outbrain, but I remember it being equally uncustomizable. If it doesn't have an API (which it does not) then we can only use it for blog posts. 

I think our options are:

1) Custom algorithm (I'd rather do this)
Such as 3 of the top voted posts for the last 30 days + 3 related posts based on tags or categories

2) Chartbeat

**Comment by JonBrooksX** [comment]
On point 1: If you make your own algorithm could you target social shares rather than upvotes? Or better still, both?

**Comment by MSchirp** [comment]
Alright, did some more googling on this and it seems gravity.com does exactly what we want. Individual recommendations based on history, relevance and evergreen content. I've contacted them to get a reply.

**Comment by MSchirp** [comment]
Gravity got back to us saying we're too small. Fuck them, lets keep growing and buy them.

**Comment by jetlej** [comment]
Yeah I already applied for gravity a while back. Fuckers!

Including social shares would be beyond the scope of what I can do before Wed. That's something that we should outsource to the new dev. Speaking of that, I'll put out a job description on eLance today!

So what should the algorithm be in the meantime?

**Comment by MSchirp** [comment]
What are your thoughts on this: https://www.sajari.com/recommend ? @jetlej

**Comment by MSchirp** [comment]
Something else I found, not sure how feasible this is. http://blog.mortardata.com/post/82195614895/giving-away-our-recommendation-engine-for-free

We can always extend chart beat for another month if we can't find a solution now.

**Comment by JonBrooksX** [comment]
Have you guys every heard of polar? 

https://www.similartech.com/technologies/polar

It's free, apparently, and pretty good. Not sure if it suits what we're looking for though.

**Comment by MSchirp** [comment]
Just checked and it doesn't do what we need.

However, I found this which is exactly what we need: http://www.evergage.com/solutions/content-publishing/

Or, as previous mentioned, this: https://www.sajari.com/recommend

**Comment by MSchirp** [comment]
Requested a demo of evergage. Will move on to other tasks now and get back to this later.

**Comment by jetlej** [comment]
Sajari would be $247+/mo because of the number of posts we have. Possibly even $497/mo. 

Evergage looks like shitty software. Most likely just barely customizable widgets. 

We need to come up with a basic algorithm now, and later you can come up with an advanced solution with the Filipino developer. 

@MSchirp @JonBrooksX

**Comment by MSchirp** [comment]
I do think $250 a month is worth it compared to our own algorithm, and it seems to be a lot less work than coming up with an algorithm that needs to be replaced anyways. 

I can't judge the evergage software.

**Comment by jetlej** [comment]
Except that we've been saying that Chartbeat always shows the same articles. It's not a great algorithm. Right?

This is taking too long, so I'm just going to come up with the algorithm. Since we're still using upvotes as 'Loves', we can use this algorithm:

5 posts with most loves during the last 24 hours

This will actually work better than Chartbeat since it actually takes views and 'Loves' into account (since every 1000 views =  a love, or whatever it was). 

Bueno?
