### ISSUE TITLE
Pop up

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#103]
1) I love the Facebook countdown after you sign up with your e-mail. but I think we're missing out on a huge group of people who find that liking our page is less of a commitment. Can we have the Facebook pop up show up even if you don't sign up with your e-mail? So it will pop up always, with clicking away, clicking no thanks etc. ?

2) I also think it should pop up 15 seconds earlier than we have now. My guess is that this way we easily target ±30% more of our audience. Yes, I know that these are probably less value, but we should go after them nonetheless.

3) Pop ups shouldn't pop up if you're logged in. 

4) Garik requested to make a special e-mail list for people who want to opt in just for updates/exciting new projects etc (beginning with the Magazine). He wanted to have this site wide. I disagreed with this because I think a huge amount of people wouldn't care less, but perhaps would care to like our fb page or even sign up on a normal content e-mail (normal pop-up). So we agreed, if possible, on having a special pop-up just for all the blog posts leading up to the launch of the magazine. Is it possible to have a special pop up just on a few pages? If not, it might be worth to consider leadpages to set this up. @JonBrooksX 

Their designer made this:

![2](https://cloud.githubusercontent.com/assets/13124056/10246027/cbe7a3a0-690d-11e5-8854-91631be15432.png)

**Comment by JonBrooksX** [comment]
1) Yeah, I agree. I did want this feature from the beginning. FB shows up whether you sign up or not. 

2) Leadpages gives you 'exit intent'. Sumo me gives you 'smart' pop ups. I think these behavioural timers are always preferable to a set number of seconds. 

3) Agreed. But only if there are clear subscription forms elsewhere on the site. There will be on HE 6.0 so that's fine. 

4) I like the "HEthen Insider" soundbite. Personally, I think we could do a lot more with our existing email leading up to a launch. But that custom pop up will target customers more than readers and give us a better idea of what we're working with. It might be worth also experimenting with pre-sales with different products. Any thoughts on that?

**Comment by MSchirp** [comment]
3) People who sign up on HE automatically get signed up to the mailing list, so this is unnecessary. 

4) They still insist on having a trial period with the design they proposed. Could you implement this and write a quick protocol so I will be able to switch back and forth, @jetlej ?

**Comment by JonBrooksX** [comment]
3) Oh, is this right? Shouldn't we need to ask them first? @MSchirp

**Comment by lostboyevsky** [comment]
yeah, like jon, my instinct is actually that we shouldn't just add new users to our email list without expressly asking them if they'd like to receive emails. probably makes us seem spammy to quite a few people

**Comment by JonBrooksX** [comment]
Or you could make the default to get emails but have the option to "not recieve emails".

**Comment by jetlej** [comment]
1) I think people are used to be auto-signed up for newsletters when they join a site. ProductHunt does this, for example. The only change I think would be good is signing them up for weekly emails instead of daily so it's not so intense all at once. 

2) RE: Maybe we should show the FB like button popup first, and then show the email popup after a few page views? Or their second visit?

Overall I think we should switch to a service like Leadpages or whatever so you guys can continually iterate and A/B test these popups. They are very important.

**Comment by jetlej** [comment]
Edit: It looks like Weekly IS the default list for new signups right now

**Comment by MSchirp** [comment]
1) I agree. Standard opt-in is the way to go if people register @ HE.

2) I like FB first, e-mail second. 

re: leadpages: Im seriously considering this option now. But few things I can't find: A simple like us on FB pop up. Is this possible with leadpages @JonBrooksX ?

Also, showing one pop up version the first visit, and another the second visit, is this possible with leadpages @JonBrooksX ? 

I know you're a big fan of them and really want to get this service started and build a huge e-mail list. I agree this will be great if we really utilise it constructively. Can you figure this out and take this on? :)

**Comment by JonBrooksX** [comment]
I've seen lead pages templates that are specifically desgined to capture FB fans, so yes. 

> Martijn: Showing one pop up version the first visit, and another the second visit, is this possible with leadpages? 

I don't have a conclusive answer to that question right now. However, I think that even if that option is not availble, there will be things you can do with leadpages that we haven't even thought of yet. It's also great for running competitions on FB—it intergrates really well with FB. 

I can take this on. I would like to start using it after the launch of HE 6.0 though. Is that cool? I don't want to be juggling too many balls at once. I'll also start doing some research on case studies. Leadpages has a great blog with a ton of useful ideas for getting the most out of their service.

**Comment by jetlej** [comment]
@MSchirp - There is *definitely* a service out there that allows for us.

**Comment by jetlej** [comment]
I'm going to close this and create a to-do on Jon's Trello instead bc this is no longer coding related

**Comment by jetlej** [comment]
However I will make it pop after 60 seconds instead of 90 + make sure it does not pop if you're signed in

**Comment by JonBrooksX** [comment]
Noted. Sounds good.
