### ISSUE TITLE
E-mail logo not fixed and random text in subject line

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#162]
See screenshots:

Daily boosts still visible:
![screen shot 2015-10-30 at 15 14 41](https://cloud.githubusercontent.com/assets/13124056/10847820/fee5b992-7f18-11e5-834e-42e31d90a4d9.png)

number of posts go here
![screen shot 2015-10-30 at 15 14 33](https://cloud.githubusercontent.com/assets/13124056/10847821/fefffb04-7f18-11e5-8238-e72bba31853c.png)

**Comment by jetlej** [comment]
Strange, it was showing the old logo if the source URL did not include www. That's fixed.

For the subject line text, it will now automatically use the titles of the included blog posts. For the 'Basic' template, there is an editable text area at the very top of the template that you need to edit in order to choose what text shows below the subject line. 

@MSchirp @JonBrooksX

**Comment by MSchirp** [comment]
@jetlej Just tested everything, the daily mail looks good to go. 

The basic show more than the editable text area on top. See screenshot:

![screen shot 2015-11-05 at 16 37 55](https://cloud.githubusercontent.com/assets/13124056/10972939/bffc32d4-83db-11e5-83f8-77aece8535ce.png)

**Comment by MSchirp** [comment]
weekly and monthly look good too

**Comment by jetlej** [comment]
@MSchirp - Can you clarify what you mean by 'show more than the editable text'? Looks like it's not showing any of it from your screenshot

**Comment by MSchirp** [comment]
Sure for the confusion: The screenshot shows the edited text 'Something wicked is this it?'. But on top of that, it also shows 'Title Unsubscribe .... address...' The latter shouldn't show up.
