### ISSUE TITLE
Comments take a long time to load/show up.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#19]
Would be cool if they appeared instantaneously when someone clicked 'Submit.'

**Comment by jetlej** [comment]
@dpatil-gmcs - Will have to alter the ajax comment plugin so that it creates a dummy comment from the data right away, and then replaces it with the response from the AJAX call once it is successful.

**Comment by dpatil-gmcs** [comment]
@jetlej : 

1. I see a couple of plugins enabled that are used for Ajax Commenting : "Ajaxed Comments" and "WP Ajaxify Comments"..Which one are we using ?

2. Also, in reference to your approach, do you think it would make sense to FLASH the Server Error / DUPLICATE Comments (which we would know only after the ajax response) and remove the comment ?

I think we should identify the reason behind a SLOWER AJAX response from the server. Do you think it makes more sense in investing time on looking at the code in wp-comments-post.php for why it causes the time lag ? Thanks !

**Comment by jetlej** [comment]
@dpatil-gmcs 

We're using both. One is for ajax editing, the other is for ajax replying. 

Yes there should be an alert of some kind to let the user now why there comment has been removed if there is an error. 

Hmm that's hard to say. I don't think there is anything to improve with the Wordpress core files,but maybe spend a little time looking around the AJAX plugin to see if there is anything that would make it slow?

**Comment by MSchirp** [comment]
@dpatil-gmcs bump!

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej 
We have implemented the aproach suggested by @jetlej  and committed the code to the PROD branch with the commit# : 09323c8a
The changes are reflected on staging site and seems to work as expected, Please have a look and let us know your comments on it.

We have tested the following Scenarions:
1. A new comment added to post
2. Duplicate comments added to post
3. Blank Comment added to post
4. Ensured that comments are working for every post loaded on the single post page.

**Comment by MSchirp** [comment]
@dpatil-gmcs What kind of changes did you implement exactly? I am unsure what to test now. And because I found an error on TEST I am not sure how to continue.

On test, I can only reply to the first comment, but not on the reply of the comment. On live, I can do this. 

See screenshot:

This is TEST. I can't reply to the second comment:

![screen shot 2016-02-12 at 16 53 30](https://cloud.githubusercontent.com/assets/13124056/13011867/3a8ce4b0-d1a9-11e5-9765-d7dbe441bd87.png)

This is LIVE, I can reply to the second comment:

![screen shot 2016-02-12 at 16 53 41](https://cloud.githubusercontent.com/assets/13124056/13011901/438221d4-d1a9-11e5-984a-b5038905a443.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp : With regards to your comment belo : " **What kind of changes did you implement exactly? I am unsure what to test now. And because I found an error on TEST I am not sure how to continue.**"

It has nothing to do with the code we have checked in...It was a PLUGIN Setting that needs to be done via WP-ADMIN...Probably, a few developers from your side probably making plugin config changes to the LIVE Site only. Hence the difference :)

The configurations are emulated to Test Site and now you should see the REPLY button as you see for LIVE.

Please verify this current issue and let us know, that way wee CLOSE it. Thanks !
