### ISSUE TITLE
quotes aren't being shortened for the front page

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#196]
this used to work. if you posted a quote that was too long it would blur it out and shorten it for the front, and you would have to click on it to read the whole thing. that's not working now.
![screen shot 2015-12-06 at 10 43 51 pm](https://cloud.githubusercontent.com/assets/9164601/11619228/046957f6-9c6b-11e5-9e4c-b0ba02aafb9c.png)

**Comment by jetlej** [comment]
@dpatil-gmcs - Please add a max length to the quote area show above so it's length is about equal with the sections on either side of it. Place an ellipses after if it has been shortened.

**Comment by dpatil-gmcs** [comment]
Just want to share a few things : 

Observation :
1. We have setup the site locally by cloning the PROD branch. The Quotes work as expected with that BLUR effect (meaning content blurs after a desired length). However, the same code does NOT work on PROD which indicates that chances are someone manually changing the code on he Live Site ?

Local Setup Code works : http://screencast.com/t/uE53JzGW

Suggestion : 
Could you please verify if the CODE in the highexistence/wp-content/themes/hethen/homepage-featured.php file is same as the one in BeanStalk PROD branch ? Because, that effect is nice and makes no sense to add the ELLIPSIS instead of the Blur effect.

NOTE : We have already implemented the ellipse code recommended above locally. But want to be sure that files on PROD Branch and LIVE Site are in sync and noone has manually edited them. Thanks !

**Comment by jetlej** [comment]
Ah yes I forgot that we had that blue effect. I wonder why it's not working on the live version...

No one is manually making changes to the live site. Everything is done through beanstalk deployment.

**Comment by lostboyevsky** [comment]
this remains unfixed for me, fyi

**Comment by dpatil-gmcs** [comment]
@jetlej @lostboyevsky : Code has been checked in to PROD Branch with Commit # : 03ae6670
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by jetlej** [comment]
@dpatil-gmcs - I think 30 characters may be too short. How did you determine that number?

**Comment by dpatil-gmcs** [comment]
"Please add a max length to the quote area show above so it's length is about equal with the sections on either side of it. Place an ellipses after if it has been shortened."

The suggestion proposed by you would mean a totally new approach...What we extracted form your discussion is that we need to LIMIT the text from not falling beyond the sections on either side...With that in mind, we think 30 - 35 is a decent WORD Count (as the Quote Font Size is slightly bigger than its neighbouring sections).

Please let us know if you have a different thought on this one. Thanks !

**Comment by jetlej** [comment]
@MSchirp - You'll have to test this one the homepage is fixed

**Comment by MSchirp** [comment]
@jetlej To clarify, figuring out the right max length?

**Comment by lostboyevsky** [comment]
i think deepak is right that 30-35 words is the correct range. the current quote fills up the space and contains 35 words, including author name

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
