### ISSUE TITLE
Front page testsite [hiexistence.com] isn't showing up properly for me

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#212]
See screenshot. It seems it is an outdated and bugged out version. I can therefore not confirm changes made to this. 

![screen shot 2016-01-11 at 15 24 14](https://cloud.githubusercontent.com/assets/13124056/12235980/8e1817da-b877-11e5-8d8c-076f07daca28.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
As per our discussion with @jetlej here is what he had to say : 
" This is because the staging site doesn’t have a pinned discussion, so it’s messing up the HTML. I can fix this once I can login."

This issue has a dependency on the Password Reset Issue for which WE need FTP Credentials for Staging...When we login with the ones provided to us, we see a BLANK ROOT Directory. Awaiting confirmation from your end on #204

**Comment by dpatil-gmcs** [comment]
@jetlej : The (Prod / Staging) UI mismatch issue still remains on Staging. So how are we planning to fix it ?
