### ISSUE TITLE
infinite scroll not working on homepage 

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#234]
i'm seeing a 'Load More' button that i need to click to see more posts now instead of the automatic infinite scroll

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  I have removed the load more button and added the Infinite scroll on the  Home page,
This task is implemented and the changes can be seen on TEST site.
The code is committed to the PROD branch with the commit#: 466708a7
Please have a look and let me know your comments so that I can deploy the changes to the LIVE.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs I just checked, and it looks like the infinite scroll is working correctly on the test site. Go ahead and push it live. : )

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  THe changes are updated to the LIVE site and Tested, The bug is fixed on LIVE now, closing the issue.
