### ISSUE TITLE
Our "related URL" functionality for in-post "Read this:" recommendations doesn't open posts in a new tab

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#268]
For blog posts, we can enter the following shortcode to insert a "Read this: '[BLOG POST TITLE HERE]' recommendation into a blog post:

[related url="http://highexistence.com/10-reasons-you-should-never-get-a-job/" title="10 Reasons You Should Never Get a Job"]

When one adds one of these, the links created *do not* open in a new tab, and there seems to be no way to manually change this. I think they should open in a new tab.

**Comment by MSchirp** [comment]
agreed. Will add this to Deepak's priorities soon.

**Comment by dpatil-gmcs** [comment]
@MSchirp @lostboyevsky  We have researched and tested the problem on few of the posts, on site.
We found that the URL's are working fine:
For reference: http://highexistence.com/10-books-will-change-live-life-forever/
Please see the 'READ THIS' section in the above post. I have even tried inserting the shortcode in the article and it seems like the post is correctly opened.
Please let me know your views on it, and if you still find some error, Please provide us the URL of the post so that we can have a look at it.
If the problem looks like it is fixed, please give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
@dpatil-gmcs Yes, the links load fine! That isn't the problem, they should open in a new tab! Not the existing tab. So when people click a 'read this' link, it opens up in a new page. Does that make sense?

**Comment by dpatil-gmcs** [comment]
@MSchirp  Yes, it makes sense. I will implement it and open it in the new tab.

**Comment by MSchirp** [comment]
Great!

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky   We have made the link open in the new tab, Please have a look and give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
Please push to live

**Comment by dpatil-gmcs** [comment]
@MSchirp  The code is deployed to LIVE site. Tested and its working fine.
Hence, closing the issue.
