### ISSUE TITLE
Fix soft 404 and server issues

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#277]
See mail I forwarded.

**Comment by dpatil-gmcs** [comment]
@MSchirp   I am going through the links that are given by the google webmastertools. I found that some urls are present on HE, but google suggests to redirect it to 404.
We are investigating the URL's and will update you as soon as we are done, so that you can ask your sever guy to add the redirect rule.

**Comment by MSchirp** [comment]
This also happened at the same time that the log in issue started. Perhaps it was the same cause?

**Comment by MSchirp** [comment]
@dpatil-gmcs

**Comment by dpatil-gmcs** [comment]
@MSchirp  It might be the same cause, but now that we have changed the settings for log in issue. Lets observe it carefully for few more days and see the result.
Let me know your thoughts on it!

**Comment by MSchirp** [comment]
Sounds good, can be closed.
