### ISSUE TITLE
URGENT BUG: screen going totally blank when you scroll to bottom of articles

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#289]
when one scrolls down to the bottom of an article, the entire screen goes blank and you have to refresh the page to get it normal again. not sure if this is happening on all pages or just some. it's happened to me several times on this page: http://highexistence.com/the-nomads-fountain-of-youth-travel-as-a-means-of-expanding-time/

i'm on a Macbook in Chrome browser.

seems to only be happening on that page for some reason.

**Comment by MSchirp** [comment]
Happens to me on Safari too

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky  it Happens to me on Chrome. When I investigated the code I realize that there is something related to chartbeat which is causing problems.
Has any one of you added a new plugin, or changed any settings which relate to chartbeat?
@MSchirp  I think we had a issue before, which was related to chartbeat and the problem was because of a plugin settings which you had installed to show ads on mobile devices.

**Comment by MSchirp** [comment]
@dpatil-gmcs No new plug ins have been added, chart beat code has stayed the same, see 'Settings -> insert footers and headers'

Please note that chart beat is implemented site-wide, so it doesn't make sense there is just one page experience this problem. Please have a look to check whether there is some specific to that blog post. Can you also have a look @lostboyevsky ?

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky  I have investigated the post content and other related settings, I think there was some problem during the publishing of the post.
Is is possible for you to delete the post and repost it again, I think the problem must be solved after doing it.
OR
can you please give me the steps you followed while publishing the post so that I can reproduce it on my local site.

**Comment by lostboyevsky** [comment]
@MSchirp @dpatil-gmcs . . . I took the time to recreate the post and delete the old one, and the problem is still happening : ( 

guess we may just have to leave it if we can't figure out what's wrong . . .

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  Can you please let me know the steps you followed to create the post?

I had tried to create the post and I kept same tags and categories, but I did not face any such issue.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp  Any updates for us?

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  I tried to debug and find out the problem, I found that the problem is happening because of the following script:
document.getElementById('ShopifyEmbedScript') || document.write('<script type="text/javascript" src="https://widgets.shopifyapps.com/assets/widgets/embed/client.js" id="ShopifyEmbedScript"><\/script>');

I did not find the script in the post content, and neither the script gets loaded for other posts. Can you please let me know if somebody has injected the Shopify related script in the post through some other means.

**Comment by MSchirp** [comment]
Good to know, Ill fix it from here, thanks!

**Comment by MSchirp** [comment]
Can you tell me how that ends up in this specific article? We only use shopify code embed script in certain articles when we want to sell a specific poster. However, that is not the case in this article, and I can't find that code within the post structure itself — therefore I can't delete it manually. (as it shouldn't be there)

**Comment by dpatil-gmcs** [comment]
@MSchirp  As you say there is shopify code embed script insered. I just revisited the post and after investigating I found that, 
The Shopify problem is not for 'http://highexistence.com/the-nomads-fountain-of-youth-travel-as-a-means-of-expanding-time/' Infact it is for the 'http://highexistence.com/carl-sagans-profound-essay-on-why-cannabis-consciousness-is-desperately-needed-in-this-mad-and-dangerous-world/' 
Which is the next post in the infinite scroll to first post.

The problem occours because the element with id 'ShopifyEmbedScript' is not found on the page while appending.

Can you please look into the shopify code you inserted for the 'http://highexistence.com/carl-sagans-profound-essay-on-why-cannabis-consciousness-is-desperately-needed-in-this-mad-and-dangerous-world/'

**Comment by MSchirp** [comment]
Ah, that actually makes a lot of sense. I will fix this, thanks!

**Comment by MSchirp** [comment]
Fixed
