### ISSUE TITLE
When people click in the text box of the email subscription form...

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#307]
When people click to enter their email address in our email subscription form, the text in the box should disappear, and the cursor should appear on the far left side of the email box. Currently, the text doesn't disappear and the cursor appears in the middle of the box: 

![screen shot 2016-07-01 at 3 39 19 pm](https://cloud.githubusercontent.com/assets/9164601/16523347/472466a4-3fa3-11e6-9f47-2fa582865887.png)

This doesn't look good. Please make this small change.

**Comment by MSchirp** [comment]
Two more little points regarding this sign up widget:

- Can you make sure people are not signed up anymore in the 'daily' group, but signed up in the 'never' group?
- Can you confirm this is also happening on the front page, not just the widget on the sidebar?

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp   The bug reported by @lostboyevsky  is fixed and we have deployed the fix to the LIVE site.  @MSchirp  can you please explain 'Can you make sure people are not signed up anymore in the 'daily' group, but signed up in the 'never' group?'

Is there any never group in the mail chimp account present? I did not find any.

Please have a look at implementation and let us know your views on it, also do reply to our query.

**Comment by MSchirp** [comment]
@dpatil-gmcs 

I made a new group next to daily, weekly and monthly, a never group. I want all new subscribers subscribed to that group from now on. (it is on 'daily' now.) I checked and its visible in the plug in now too.

**Comment by dpatil-gmcs** [comment]
@MSchirp 

I have made the changes to the LIVE site. Now, the new subscriber will be subscribed to the never group.
Please have a look and give us a sign-off so that we can close the issue.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, only thing i would add to this is that we would like to have an Instagram icon on this form. you'll have to widen the space between the FB and Twitter icons a bit. try to make it so that there is an even amount of space between each border and the icons next to them and between each icon. here's a black instagram icon with transparent background that you can use for this:

http://www.iconsdb.com/icons/preview/black/instagram-xxl.png

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp 

Just and FYI, the above task is related to the #247, We have already tried adding the Instagram icon on the form,
But the problem occoured was as soon as we added the new icon the facebook and twitter icons were not displayed correctly.

Please refer the #247 for the detailed description of the problem.
Although, we shall try implementing it again as soon as we start working tomorrow, But just thought to inform you about the problem we faced earlier.

Do let me know your thoughts on it.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp 

We tried to insert the icon provided by the @lostboyevsky, But even this time we found that adding the additional icon to the project shatters the other icons too, just like in the case of #247.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, obviously there must be a way to do this. It seems that what you're saying is that you and your associates do not know how to accomplish this. If that's the case, that's okay. Just leave it as it is for now, and we can find someone else to do it.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  Just so that you know, It's the grunt file which changes the CSS and other icon related files. In this case whenever we try to insert the new Instagram icon into the project using Grunt, the grunt file shared with us shatters the icons, due to which the icons do not appear properly after adding the new icon locally.

I remember, while working on #247 @jetlej  was able to add the new image/icon following the SAME steps that we are following locally. So this obviously hints towards  @jetlej having a DIFFERRENT Grunt File, due to which he was SUCCESSFULLY able to add the icons effortlessly. 

If @jetlej could share HIS version of the Grunt File with us, we too can do the same.

@lostboyevsky Please let me know your thoughts. Thanks !

 @MSchirp : Just a gentle request @lostboyevsky, if we could CREATE NEW BUGS rather than EXPANDING the existing scope of the current issue (which was ALREADY marked as CLOSED), would help us.
