### ISSUE TITLE
Daily mail doesn't show author, upvotes etc. anymore

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#40]
![screen shot 2015-07-15 at 21 04 24](https://cloud.githubusercontent.com/assets/13124056/8707290/41125916-2b35-11e5-9e6c-80f34d230e12.png)

**Comment by JonBrooksX** [comment]
I requested the daily mail not to show upvotes and comments. It doesn't look good when out top 5 posts have like 6 upvotes and 2 comments. We should have the authors name in there though.

**Comment by MSchirp** [comment]
I think it looks very empty and ‘socially validated’ at all. Wasn’t the whole point of having views + comments count as upvotes to remediate this issue?

**Comment by JonBrooksX** [comment]
Negative social proof is worse than no social proof -- although it's in the top 5 so that assumes social proof. I don't know. Are we getting enough comments and upvotes now to use as positive social proof? HE is meant to be a monster site, I honestly think we need dozens of comments and upvotes on our feed items before we show them off. There were some items that had 0 comments. This just ruins everything in the mail. I'd say let's wait a while until the stats go up then change back. What do you think?

**Comment by MSchirp** [comment]
Alright, here is what we do: take the worst 3 and the best 3 e-mails of the last two weeks. we measure the open rate vs. click rate for those. In two weeks we will do the same for the mails after the change. Then we compare both and see which wins. This could very well be too much effort and not show any significance, so just say no if you think this is a bad idea.

**Comment by jetlej** [comment]
Btw please don't use the 'Urgent' tag unless it's something that's almost breaking the site, or really important. This is not important.

**Comment by MSchirp** [comment]
I thought it was another bug in the daily mail, hence the urgency. 

Regarding this change, can we at least show who posted/submitted it? Now it still says 'posted by' in the daily mail, but no name shows up.

**Comment by jetlej** [comment]
FIXED ON LIVE SITE :)
