### ISSUE TITLE
Discussions accepted but not on the front page

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#5]
I talked to Mr. Bates - and I agree. There are discussion we want to approve but not want on the front page. Can we have the 'to front page' (or to 'back page') option in the moderator tab?

**Comment by jetlej** [comment]
@MSchirp - We choose to make this change for a reason. Do we want to accept discussions that are just 'okay' ? Please explain the reasoning.

**Comment by MSchirp** [comment]
Yes, I remember. However, I think Bates was right when he argued that there is a subcategory of articles you want to accept - but not have on the front page. Small questions, poems, short stories, recurrent themes etc. The problem now is that by rejecting them - we deter new users from joining. 

If you disagree, and alternative would be to change the rejection text to something more constructive, as in: ‘We really appreciate your submission but unfortunately we decided against approving it. We specifically curate our current feed to meet the highest quality standards and only accept a few posts a day. Please consider resubmitting your post on a later moment and make sure you provide the most value you can to the rest of the community. We are sorry if this feels annoying, but we have found that this is the only way to guarantee healthy and constructive discussions. Thank you :)’

**Comment by jetlej** [comment]
The discussion section is you're baby, so your wish is my command. Just wanted to make sure before doing the coding.

**Comment by MSchirp** [comment]
Yeah excellent points. Ill ask other J to comment to see which side the scale tips.

**Comment by lostboyevsky** [comment]
I think people will be more deterred if their Discussion gets altogether rejected than if it just gets sent to the Discussions page instead of posted to the feed.

For the most part, I wasn't talking about amateur art/poetry. A lot of people submit pretty specific/weird questions -- like, "help me interpret this dream" or "give me advice on this really specific relationship thing" -- and although I don't want to see those on the front page, I do think it adds value to the community if they can seek an answer on HE. Such questions do tend to bring multiple HEthens out of the woodwork to provide anecdotes and reflections, which is good. 

However, I like the idea of reserving the front page for questions that are bigger, more profound, more universally relevant/interesting.

I like the idea of cracking down on totally weak Discussion posts, but I think allowing us to accept some here and there without adding them to the feed would be a worthwhile move.

**Comment by jetlej** [comment]
Good points, Jordan. I agree!

**Comment by jetlej** [comment]
I just made it so the frontpage topics on 6.0 only show those marked as a 'Frontpage Topic'. All other approved topics show as normal on the /discussions page.

Sound good?

**Comment by MSchirp** [comment]
Yes.
