### ISSUE TITLE
Change upvoting to 'Love' and add back upvoting to comments

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#57]
there is still no means of navigating to the images/videos/quotes sections of the site, seeing the most upvoted content of all time, etc

**Comment by jetlej** [comment]
I know we discussed this... what was the conclusion? Just putting it in the header navigation?

**Comment by lostboyevsky** [comment]
not sure there was one.

here's what i propose: 

we change the 'Discuss' button in the navbar to "HE Universe" or something like that and have it be a drop-down that has links to discussions, images, videos, and quotes. 

'Discussions' are already highlighted so much on the front page that i don't think we need a separate item for them specifically on the navbar. a drop-down would work, i think, and that would allow users to get to that other content

that doesn't solve the problem of users not being able to elect to see the most upvoted of all time or other parameters like that though

**Comment by jetlej** [comment]
Discussions should def remain in the nav so people can jump straight there from other pages on the site. Navigate predominantly happens from non-homepage-pages. 

I agree we need to let people see the top-all-time views somehow. Top today/weekly/monthly/year will be irrelevant bc we'll have removed voting. So we don't quite need sorting, maybe we just have a top content of all time in the dropdown for images/videos/posts?

Also, do we remove any reference to the link post type? I don't see much value in keeping an archive of those. @MSchirp?

**Comment by jetlej** [comment]
@JonBrooksX @MSchirp @lostboyevsky 

Can we decide on this?

**Comment by lostboyevsky** [comment]
i'm still in favor of their being a way to get to images/videos/quotes in the navbar... i think the links should first navigate to a page showing the most recently submitted items and then there should be a button on there to view 'Best of all time' or whatever to see the most upvoted stuff of all time. i thought we were still going to have a form of the upvote feature? i feel we should personally

**Comment by JonBrooksX** [comment]
I thought we were getting rid of the upvote feature. I laid out the reasons on slack. It hasn't been working for months and the only reason it looks moderately respectable now is because we have views=upvote code. 

I am in favour of a way to "favourite" posts that allow people to save a post to come back to HE to read. Like on the guardian newspaper app you can just "save for later". This will

**Comment by jetlej** [comment]
@JonBrooksX - But there is still value in letting people see the legacy best content on HE. That shit is good. There would not be any references to voting or vote counts, but they could still see the Top All Time list. Thoughts?

**Comment by JonBrooksX** [comment]
We also discussed this in Slack. I think the solution to this was to have a "Best of page" similar to the resource page we're working on but with the best articles. Do you think we could also come up with some kind of badge that we can slap on a post when it hits 50K+ shares? We were posting "must read" on every article in HE 5.0, would be nice to have a way to separate the viral content from the others. What do you think about that idea?

**Comment by jetlej** [comment]
I did away with Must Read bc it was being overused on the current site. I like the 50K share idea. I'll add that as another task, semi-unrelated to this one. 

Or should we combine the two and just have a list of all the content by most shares? Forget about the old votes completely? Probably best to simplify...?

**Comment by lostboyevsky** [comment]
i think the most upvoted content list is really valuable and interesting to look through, personally. also, i want to keep upvotes because it's just a super simple way to express that you appreciated something. i like being able to upvote, and it's cool that it's native to HE. i've personally always used the upvote mechanism on HE, even when it was the 'Love' button back in the day. even if upvotes are only used by super users, i still think they improve the site

**Comment by jetlej** [comment]
@lostboyevsky - This is news to me, I thought we had decided to change the upvote function to 'Favorite' weeks ago. Were you not present for this convo?

**Comment by MSchirp** [comment]
I liked the favorite idea IIRC. Couldn't we just use these for the 'top lists'?

**Comment by lostboyevsky** [comment]
if 'Favorite' can still function the same way as an upvote for all types of content, and we can track which content has the most 'favorites' to continue compiling the top posts/images/videos/etc., then i'm probably cool with 'favorites.' i do still like being able to upvote comments and stuff though -- i use that feature constantly. 

i was present for that conversation, and i think at the time i was cool with it, but i guess i just changed my mind after really reflecting on how much i use the upvote feature and why i think it's valuable for the site. sorry to flip flop. if you guys want to press onward with the previous plan, that's cool. either way will be okay, but my vote is to keep upvoting.

**Comment by jetlej** [comment]
@lostboyevsky - To keep it for everything? Comments? Discussion replies? I like it for comments/replies, not sure about normal content. I'd rather have them share it on social media than click upvote.

**Comment by JonBrooksX** [comment]
So I use the guardian app quite a lot and there is a 'save for later' option, and share options. I think this is simple and functional and something we ought to imitate. I respect that you use the upvote button Bates. Unfortunately ever since I've been working for HE it just hasn't been working for the majority of users. We did gave it a fair run, even added view:upvote counters and even with that it didn't represent a site that gets 3 million page views. If anything it looked like negative social proof. 

I say ditch upvotes for posts, instead focusing on comments and shares. I think for posts we shouldn't 'show off' the favourites. I think it should be visable at the bottom of the post like it is on medium articles.

I would really like to remove upvotes on EVERYTHING, actually, until our community is thriving again. Then I'd opt for adding them back in. In short, we've tried upvotes. they didn't work. Remove them.

**Comment by MSchirp** [comment]
What is essential to get to the discussion healthy again is to remove the threading. It confuses the hell out of browsing through them (for multiple reasons). (I know I mentioned this before but forget to check up if this is already done. Will add new ticket for this because it's not.) Besides that, regarding discussions, I think the old system of loving worked fine. But it didn't add that much so I am also ok with removing it. 

I like the save for later idea. And I agree with Jon, we don't want another negative social proof fiasco. So remove.

**Comment by jetlej** [comment]
I see two options: 

1) Save for Later -- questionable value because of apps like Pocket (if you don't use Pocket, you seriously should. Totally changed how I consume content and created an easy way to save something instead of being distracted whenever I see something cool)

2) Change voting to something like Medium.com has, eg. 'I appreciated this post'. Something very HE. Big nice button. Oh wow, apparently Medium just changed their big button to a small heart icon! I wonder why they did that...

**Comment by MSchirp** [comment]
I go for two, love the love button.

**Comment by JonBrooksX** [comment]
2 works for me. I don't see that much of clash between pocket and HE though. Pocket is for infomation consumption not communicating with likeminded individuals. I still think there should be a way to "favourite" or save posts and discussions so that you can navigate back to them quickly. Especially older posts. That way you reserve the "love" or "favourite" button for posts/discussions you really want to keep an eye on over the following weeks. There should also be a way of seeing this easily from your profile page. I want people to have logged-in privalages beyond commenting.

**Comment by jetlej** [comment]
@JonBrooksX - You'll still be able to see the posts you upvoted/loved/favorited, so this accomplishes both

@lostboyevsky @MSchirp - What verb should we use for the new button?

**Comment by lostboyevsky** [comment]
@JonBrooksX i do see what you're saying about 'negative social proof', though i also think leaving upvotes for comments/replies doesn't hurt anything and gives users an easy way to express approval/appreciation of a comment

i'm okay with removing upvotes on everything else and adding the button at the bottom. i'd be in favor of going back to the 'LOVE' button. could be a cool way to have HE 6.0 pay homage to the earlier day of HE, show some continuity, invoke nostalgia

**Comment by JonBrooksX** [comment]
• I don't have a huge problem with leaving upvotes on comments if you really want it @lostboyevsky.
• Love button at the bottom is cool.

**Comment by jetlej** [comment]
@MSchirp - Alright so are we all good with upvotes on comments and 'Love' at the bottom of articles?

**Comment by jetlej** [comment]
And are we keeping upvotes on comments but not on discussion replies..?

**Comment by lostboyevsky** [comment]
i would personally suggest keeping them on discussion replies too.

**Comment by jetlej** [comment]
@MSchirp and @JonBrooksX

**Comment by JonBrooksX** [comment]
I think it would be weird to have them on one and not the other. Because upvotes on comments don't negatively impact social proof if they're low, I'm in favour of keeping them... but only if it adds to the user experience. So if you remember, I referenced Quora's comment area a few weeks back. They have their "upvote" option BELOW the comment with a clear "upvote" sign. Would definitely be in favour of copying this. I think that's great UX.

**Comment by jetlej** [comment]
I just added back voting to comments/replies and put them below the text like Quora.
