### ISSUE TITLE
Discussion threading, categories and main page.

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#94]
First, discussion threading (see attachment). I remember we discussed this to remove this and have our forums linear again. As it is now it ruins any possibility of large threads, simply because you can't keep track of what is new or not, which causes you to search endlessly, which is very annoying. I think we should default back to what it was. New post go on the bottom of the queue. 

Second, I think we should remove all categories. They don't match the other categories of the site, don't make sense anymore (yeah I know I came up with them, but I can see now these were idiotic), and are rarely used properly. Simplify.

Third, the discussion main page is very bland. (see: http://hiexistence.com/discussions/ ) I feel there is something essential missing still, and I feel we're missing out on a huge opportunity to direct them to something they like, and keep them circulating, again and again. There is no hooked cycle to be found here yet, so perhaps we can add the following modules on that page so it becomes more of an overview of what is happening and what has happened on discussion:

Latest discussions + Most Active (most comments last 7 days) + Vocal Users (List of users who replied the most last 7 days) + Top discussions all time (most comments all time)  

In a way, I think this page needs to be pre-formatted in a way that highlights unique subcategories of our discussions. Especially in a way to adds social proof and shows activity. 

@jetlej @JonBrooksX @lostboyevsky

**Comment by jetlej** [comment]
1) Not sure I agree with this. I remember defaulting to your opinion back then bc the discussions was your special area, but now I feel more opinionated. Linear discussions also make it impossible to have more than 2 threads in one discussion, which makes it confusing. I think there is an ideal solution to this in making it easier to find new comments rather than resorting to the stone age. 

2) Agreed

3) Great idea. I'll implement this.

**Comment by MSchirp** [comment]
From what I’ve noticed in my activity in discussions, as well as heard from the moderators who all left after a while, is that the fact that it is impossible to have more discussions in one thread actually makes it more reliable. What are your thoughts on another ideal solution?

Another point:

4) Can we have a good quote system? Right now it is impossible.

**Comment by JonBrooksX** [comment]
I'm not clear what the problem is with discussion threading. I can't see a screenshot. 

I like this system for discussions: 

- All newly made posts go to the top. 
- All newly commented posts go to the top. 
- Certain discussions can go "sticky" if they get X comments in X timeframe which give them a special label and keeps them in the top 10. 

I also think there should be comment rules. 

- 25 commetns for adding URL. 
- 50 comments for inserting videos. 
- 100 comments for (something cool)

**Comment by jetlej** [comment]
@MSchirp - Alright that's a good point. Is there a website out there with discussions we'd like to model? I don't want to revert just bc discussions were more active before. We changed a LOT of things about the size, and any # of those things could have been what decreased engagement.

**Comment by lostboyevsky** [comment]
one of the big problems i have with the current discussion format is that it's difficult to tell (and this goes for both 'Discussions' and comments on blog posts) when a comment is a reply to someone else vs a general reply to the thread.

i think we should take a page from reddit's book and initiate the simple solution of having replies *indented significantly*. any reply to a comment on reddit is indented significantly so that it is immediately visually obvious that it is a reply to another comment, rather than a general reply to the thread. this makes scanning reddit comments much easier than HE comments. i think new comments that are general replies to the thread should appear at the top of the discussion, whereas replies should appear beneath the comment they're responding to

**Comment by lostboyevsky** [comment]
definitely in favor of martijn's second and third points

**Comment by jetlej** [comment]
@lostboyevsky - How is that not what we have already? Indenting and putting replies below the comment they replied to?

**Comment by jetlej** [comment]
@lostboyevsky

**Comment by lostboyevsky** [comment]
the main difference was contained in the word "significantly." as it stands, i can barely ever tell if someone has replied to a comment or just posted a new comment because the indentation is infinitesimal. i think we should indent a full 2 cm or so to make it really clear which comments are replies

**Comment by MSchirp** [comment]
Are we sure a bigger indent is the solution? I personally am not convinced. Even with that, once the discussion becomes bigger and you see a notification of a new reply, you have to search for the reply. This is what in Hooked called not living up to the expectation, which breeds annoyance. 

I think figuring this out will be very important for the future of HE. 

Our old forum had no indents.

Facebook has a max of 1 indent.

Reddit has infinite indents. Although at a certain point these are minimised too.

Perhaps we can analyse the implications of the different options? I think if Facebook had more it would become a mess, too much in between commenting, not enough space. I think we are a bit between FB and reddit, perhaps we should cap threading at 2 max? Would that work?

**Comment by lostboyevsky** [comment]
i would be in favor of capping threading at 2 max. is there no easy way to make our notifications function in a way such that when someone clicks on a notification of a reply it takes them to the specific reply within a thread?

i think a bigger indent or some way of making it more clear what is a reply and what isn't is a necessity. i agree that this still leaves something to be desired if people have to search through the conversation for new replies. i think if there is any way that notifications can be linked directly to the specific new reply, that would be ideal. or, perhaps, the new reply could be highlighted when they go to the thread in question.

**Comment by jetlej** [comment]
I agree with @lostboyevsky. It sounds like this is more about the difficulty of finding your reply, which should be solved with the notification linking directly there. In fact that's how it should be working now. It appears to have broken at some point. This is something the new dev should fix.

**Comment by JonBrooksX** [comment]
Have you ever considered a forum design that is more like bodybuilding.com: http://forum.bodybuilding.com/showthread.php?t=132306613

You can quote people, but there is NO INDENTS. Linear design. I prefer this because it creates "good threads" that in themselves are worth reading. I prefer this to our current forums. 

What do you guys think? @jetlej @MSchirp @lostboyevsky

**Comment by jetlej** [comment]
I personally dislike old forums layouts like BodyBuilding.com. Why not just see direct replies to someone's post right underneath it? I think that site is useful because it has good content, not necessarily because of the "linear" conversations.

**Comment by jetlej** [comment]
I'm also in favor of going the Facebook route and having only 2 levels of replies. Keeps it simple while removing the requirement to quote, which makes no sense to me.

**Comment by lostboyevsky** [comment]
yeah i'd say i'm staunchly in favor of seeing direct replies to someone's post right beneath the post

**Comment by jetlej** [comment]
+1

@MSchirp

**Comment by jetlej** [comment]
Let's also go back and discussion Martijn's idea for formatting the /discussions page

> Latest discussions + Most Active (most comments last 7 days) + Vocal Users (List of users who replied the most last 7 days) + Top discussions all time (most comments all time)

I'm picturing 3 columns at the top, with the normal *Latest Discussions* full-width below those columns. Any comments/suggestions?

**Comment by MSchirp** [comment]
- 2 level of replies is good only IF the notification would work perfectly. Which we need a dev for. If that doesn't work, I would argue for 1 level reply maximum. I am 100% convinced it would become too chaotic with just 2 already. 

So basically: 2 level of replies with notifications > 1 level replies > old bodybuilder forum > 2 level of replies without notification. 

- In either case, also making the indents more clear (bigger change in color/distance.)
- If possible, a good quote system would definitely be helpful. People who use quotes are always more structured and eloquent, I find.
- What @jetlej pictured is the best way to do it, I think.

**Comment by JonBrooksX** [comment]
In agreement with Martijn. Good quote system would also be cool. Would it be possible to copy standard emails, in that when you highlight text and hit "reply" it creates a quote of that text in the reply?

**Comment by jetlej** [comment]
@MSchirp @JonBrooksX @lostboyevsky --- Check out http://hiexistence.com/discussions :)

**Comment by JonBrooksX** [comment]
THAT LOOKS AWESOME! Seriously fantastic. Discussions are back! :)

**Comment by JonBrooksX** [comment]
One thing, the first category says "most active posts this week". For consistency, I'd rather see here "Top posts this week" and so then "top posts ever" and finally, "top users this week". Not sure if "active" has the same appeal as "top" from a user standpoint.

**Comment by jetlej** [comment]
Good call. Although now that I changed it, the title kinda look similar. I think I prefer variety. Thoughts?

**Comment by JonBrooksX** [comment]
I see what you mean. I like column 1 and 2, but would be happy to see "top users" change to something else. 

Ideas: 

"DISCUSSION LEADERS OF THE WEEK" 
"MOST ACTIVE USERS OF THE WEEK"
"MOST ACTIVE HETHENS OF THE WEEK"

**Comment by jetlej** [comment]
I like Discussion Leaders :) I changed 'Top Posts of this Week' to 'Hot Posts This Week'

**Comment by MSchirp** [comment]
This looks fantastic!

1) Top Posts Ever doesn't make much sense to me anymore. This will become too static. We should either change this to 'Top Posts This Month', or, perhaps better, 'Latests QOD's', then link to the QOD's there with the # of replies. Thoughts?
2) Could we a little bit more color here? It's a bit too much like 5.0 and not enough 6.0 . Something akin to this: http://hiexistence.com/topic/a-new-discussion-about-badges/ (or a random suggestions, have a real time map of people who visit HE to give a sense of 'activity' on the site, see Mapping Your Visitors @ http://blog.chartbeat.com/2011/08/08/tools-for-sharing-your-data-with-the-world/) 

3) Somewhat unrelated: do we want a text with an arrow next to the like fb page on the top navigation bar? Like "Click', 'get some crack', 'enter the void'. etc.?

**Comment by jetlej** [comment]
1) Agreed on top posts. People keep posting in the 'Where are you from?' topic, and it's totally useless. Are the QOD's going to be discussions instead of images? I think they should be. 

2) What are you referring to with that first link? But yeah okay I'll spice up the design :)

3) Lol 'somewhat unrelated'? Start a new issue for that Marty!

**Comment by MSchirp** [comment]
1) Is there an easy way to implement Jon's image in a discussion? That way we could make them easily discussions.

2) yes, just spice.

3) alright.....

**Comment by jetlej** [comment]
Yeah even now he can add an image into the content of the discussion post. I'll add a category for it, and only admins will see categories when creating discussion posts.

**Comment by MSchirp** [comment]
That’s perfect. Can we still put these on the front page if they are discussions?

**Comment by jetlej** [comment]
Yes
